import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import Sidebar from "@/components/Sidebar";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function InventoryDashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={openSans.variable}>
        <Sidebar />
        <main>{children}</main>
      </body>
    </html>
  );
}
